---
nodejs_version: "20.16.0"
npm_version: "10.8.2"

python_version: "3.10.3"

docker_version: "26.1.1"
docker_ubuntu_version: "5:{{ docker_version }}-1~ubuntu.22.04~jammy"
docker_compose_version: "v2.28.1"
docker_users: ["vagrant"]

docker_install_compose: true
docker_compose_package_state: absent

docker_packages:
  - "docker-{{ docker_edition }}={{docker_ubuntu_version}}"
  - "docker-{{ docker_edition }}-cli={{docker_ubuntu_version}}"
  # # - "docker-{{ docker_edition }}-rootless-extras={{docker_ubuntu_version}}"
docker_daemon_options:
  log-driver: "json-file"
  log-opts:
    max-size: "10m"
    max-file: "2"
    labels: "host-{{ ansible_hostname }}"

packages_to_install: ['make', 'jq', 'net-tools', 'vim', 'sqlite3', 'cowsay', 'figlet', 'dos2unix']
