
# volumes:
#    shared_logs:
#        driver: "local"
#    upload:

services:

### HTTP gateway    #######################################
### Proxy container #######################################

  traefik:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.rule=Host(`${SUBDOMAIN_TRAEFIK}${BASE_URL}`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.services.api.loadbalancer.server.port=8080"
      - "traefik.http.routers.api.middlewares=traefikauth"
      - "traefik.http.middlewares.traefikauth.basicauth.users=admin:${PW_TRAEFIK}"

      # - "traefik.http.routers.metrics.rule=Path(`/metrics`)"
      # - "traefik.http.routers.metrics.entrypoints=metrics"
      # - "traefik.http.services.metrics.loadbalancer.server.port=8082"
      # Defined here and used in all microservices
      # - "traefik.http.middlewares.metricsauth.basicauth.users=admin:${METRICS_CREDENTIALS}"

    image: traefik:v2.11.0
    restart: always

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/dynamic_conf_mkcert.yml:/etc/traefik/dynamic_conf_mkcert.yml
      # below: we have to mount it to preserve it on the host, so no secrets
      - ./certs:/certs
      - ./certs/acme.json:/etc/acme.json
      - ./traefik/cors.yml:/etc/traefik/cors.yml
      # - shared_logs:/var/log/traefik/
      - ./traefik/logs:/var/log/
    # networks:
    #   - management
    ports:
      - 80:80
      - 443:443
      - 8080:8080

    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost:8080 || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s

    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      #- "--api.debug=true"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.entrypoint=metrics"
      - "--log.level=INFO"

      - "--log.filePath=/var/log/traefik.log"
      - "--accesslog=true"
      - "--accesslog.filepath=/var/log/access.log"

      - "--providers.docker=true"
      - "--providers.docker.swarmMode=false"
      - "--providers.docker.exposedbydefault=false"
      #- "--providers.docker.network=management"

      #for prometheus
      - "--entrypoints.metrics.address=:8082"
      #for http + redirection
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      #for https
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      #for https using the manually provided certificates
      - "--providers.file.filename=/etc/traefik/dynamic_conf_mkcert.yml"
      
      #for CORS --NB:there can only be ONE file provider at a time. Adding this will override HTTPS
      #- "--providers.file.filename=/etc/traefik/cors.yml"
